language: ruby

rvm:
  - 1.9.3

env:
  global:
    - "FTP_USER=user"
    - "FTP_PASSWORD=password"

before_install: git submodule update --init

script: jekyll build

# after_success:
#   "wget -r ftp://server.com/ --user $FTP_USER --password $FTP_PASSWORD"
