language: ruby
rvm:
- 1.9.3
env:
  global:
  - secure: fg6XVNS5SJCrE4tw+tAOQmfiI9qzaEf/CTJczKre7cO89r0ebM+y2itpeVzeeKQUxPvgukN9F3X8BRdKrYQvOFaStbOomkBCI8WyTHj01l+mHoqEDIXHNSXxOYJqunvKaBqHknU9F+WWFaAebV/Uxt+C1ZLf7eHFYoHiYbb+WHE=
  - secure: WjmEN6zadUjl6Hrf4bZPBuyFRX+VXwtj0U25cQB2IbCdirEOCxiFS6gss9agmYYnDLfdCxmI1JAXWFTHmw+1dT7BhT1BPpcqTCzV2Yzwlga4xws5MDB1zsuYzVstR5QSbtp9t82guykLAQzfh7/OLDJmqnkwPkCJ/aw1E301Xvw=
  - secure: afrOVv8TE7D3w22tI24QEY1k9zDrcqLYI0UdJwXX8eE75yEHWml0AH5WvncnHrk7HD4SKVz3W1BWM3tfoI0A3yHgMyWI0Un4SZJv3khuGsZhNkgc2Q68kmtvbKZ0rQUul6AGo/S9nOYzzMHrQkHX8n0RCYEmBCyaxSDhFSzP6hQ=
  - secure: KF0gFGiBOYgNyZao+S/2Amg5phLHe7cqLIRTjklWMpd1eq0+L5Ei7mAaCylHLs3z5xmwzR3eUD63At8v2uiJ6O7zDyRKle2Y1y/6+40Q09JxQDlJco0IbHJQ9Xbq2u9bZW9owg7Qq/kiXmwRPsr/RTTGqWH1dE2bF7r29KXc5e0=
  - secure: QFWFB/E2MU2GY/oePJMKIObglxQpvpz7NV3tMTO6IyjAho+fEH6sGNaSCraSHlsCn7TI9DvRI5q/FM8C8d1nJ8hr4BoL/7AX+pdHBQeWFeQR8rzIUdXOruH2ox39rFYEoWb6rVsZ0WGUB5l1nye8AIaiLyVWiZ2eQ3t3Iqu9/3U=

  - secure: "BJNqCYEwZW+GKu8i5rfjd4wC6Scf5+KLTDkmuamYvY40CaYNSINFbNYOg8nrpwUkzcCcCgH7dtE5Ir5LiEqoYCYxLZoOKrNLIAg3/snNflP+qd4yY5lh9iWyGQcCw9Vg3Kq6ubVFkuO9nKfZv8pRoQZ/Tj73BtsEBL+OeDz51no="
  - secure: "CAQaP+rs1knS1BmKS31MPvqXjnIqN0QzCjvV3BqnRFjkLa7QUVPTCT6xr/HO6cd7veBSOtM11UKbXkj/yCMhVChNrHcWWVB8qB8k9lPWMcp3UXEEyTBDjw0LZia9XMwAjv8rK+ujxaj0buSf5hbwuy2/DCkSBxv3UGfh+91ozkM="
  - secure: "bsgFcel/jDa/FOjST43Nv02LHWF1XwXi7pYLVxA7do5cmRSB5UbqUdLmQPEP2nF4jSYBY2ZUtZDe/wVy7prd1D1r7RnZXUyWdwpKRIxFluZWe4K9I4BYiDT3Owb+U8Mc/CdGlpP5C2iEDJPURCkGj7cEJXq+qT2S1pm8J8OA5ko="

before_install:
- git submodule update --init --recursive

script:
- jekyll build
- mv ./_binaries/* ./_site
- ls -aR ./_site/*

after_success:
- echo "Host deploy_server" >> ~/.ssh/config
- echo "    Hostname ${SSH_HOST}" >> ~/.ssh/config
- echo "    User ${SSH_USER}" >> ~/.ssh/config
- echo "    Port ${SSH_PORT}" >> ~/.ssh/config
- echo "    StrictHostKeyChecking no" >> ~/.ssh/config
- echo "    CheckHostIP no" >> ~/.ssh/config
- echo "    UserKnownHostsFile=/dev/null" >> ~/.ssh/config

- echo -n $id_rsa_{1..5} >> ~/.ssh/id_rsa
- chmod 0700 ~/.ssh/id_rsa
- rsync -avz ./_site/* deploy_server:~/mysite/
