language: ruby
rvm:
- 1.9.3
env:
  global:
  - secure: "bXjukHLsCSnT86z4I47+8GZifKk5yObCMYdsWEa7x8tA318DtW/AJqXxQ3DUzMvVpzChA/AA/6TuOAopWDOtOfEVoza5e7PuYwB8QEHBIMhmF+2C1j3cVRG+8AQ73r6egvIo87ltjx26ohbQZX7wuGLglZ5CmETkOh/tFxPVJp4=" # SSH_HOST
  - secure: "jlRD8Yr0nCF4yEdx+oCgKsvb3wgFRCi3YNyLIu/CQCuJ7TfxDVcB9oX1IYST00On1VZk198sC3A4aiBlM/PN0IKg9KMf3+zW6wKc58+KgViLdZwn5CNmXVfb4KKwWDPbCtLVv5/ottJA9VOPuhAGjKzoyE/IVJlNnwdKVK2gbt4=" # SSH_USER
  - secure: "YCCh4ZT/2XhrIDRe6LGY7DumdwsZ1g+GVyjCGEzvFoE9acQVttPbIsyi6Y70ayU6pEwUY+h0sMqTy6UXDfZfFH4if9fQnlFV91lv34FZKQE/BYUftnYR7s/9SecVJSmlt9JdhBjF+PzoEzAwWvUFwok/qEXxZ1qmkI6Ih5S+uNA=" # SSH_PORT
  - secure: "EokjSeBOKUnx0pjrXL+8W7+t/XrfHj/Azn/GZ/o9OCllXeuvUrs/0mshpNdoVC88yfkxUsb7K1JDzFYS8eeKMF/JJdIqG8X7WFw1lMlIrvfiHkc3vVJb+RA3dgf2hn6x4Vr765iZwCKLLLEQEs2GFCNGE+A/Xl10QeTv0tmQWRs=" # ENCRYPT_PASS

before_install: ./_scripts/before_install.sh
install: ./_scripts/install.sh
script: ./_scripts/script.sh
after_success: ./_scripts/after_success.sh
after_script: ./_scripts/after_script.sh

notifications:
  irc:
    channels:
      - "irc.spotchat.org#NixTuts"
    on_success: always
    on_failure: always
