language: ruby
rvm:
- 1.9.3
env:
  global:
  - secure: "iSEhQ/1kw3RE9+t4K06uZAQRVq0p/Qdyr0Sd13pn17UjL3nVNBHWIs7Sf2lEXEmGtpLN6OyMk50LQsabl4kvrXwNxN2jeZ8GBJixwVmZLiKWRTVj6m3AIkYKgyK32Ns5AzJc5yUi3pDMO8pPTjQFeMCzf3jlbpylhwZbB+AhDXo="
  - secure: "SyZMEAdmE2cqWa0rgLH/PUp+mdQpxCBl26FxaCW5Oey7ldZsoAf2GA3n6rJFi0yDWGBV8ycAB6mAQKse/9CP3xziAsdF3KLtiwBuX0eFi6G73YGZryM2UHS8Rfrd5f/IT8OLKeMUar29y0SN84PkI0vJNavVlpGcINn0fPdhRcQ="
  - secure: "A/oJzTKZuWNwtk8kjz2iTbGKM1TPyDPmdKoAwjS+x0bKAwIAUUpUWTKy8DRHtGYfPXkL1hHlzmXClmWIic6MHv9QHHbGTnEDuyGJzhANSS5vSgX9MkhDuxBoPbfZoHIgtdYgjmpPggWT+c0Wyjf41PL2gesYJAGJO3+Lsr2Golk="
  - secure: "gsqKnnSjyQhF9ayyCJ5Kig0cI9yziW6AshFl/7FK7lrGSJmJzljtilZoH/j2dr9Mlxt1PzOwDLvziuMYOyLE6J+8XQ1RyEulmdBsopAzVuckYm35PFIMrmvAgAwunpxFp2a7AuLpi0UN7+SrmcriII89psdASGVaEoFgLwn+XXQ="
  - secure: "NNpKktlFqISJP3i80jdn6oAJgFNtJPL65rDU7OYjmXP5V92o32WDFQa8btEtkAfPMQx0TXoD8Vf7BbF9WjcQxqNmDgBn/BjAeEwif0QsyqVpkyfS9LTB25h5/xervHW/ezXf4jX5IadugELmzYDjgMOuWIbhQRnEwDkAh5m/o78="

  - secure: "BJNqCYEwZW+GKu8i5rfjd4wC6Scf5+KLTDkmuamYvY40CaYNSINFbNYOg8nrpwUkzcCcCgH7dtE5Ir5LiEqoYCYxLZoOKrNLIAg3/snNflP+qd4yY5lh9iWyGQcCw9Vg3Kq6ubVFkuO9nKfZv8pRoQZ/Tj73BtsEBL+OeDz51no="
  - secure: "CAQaP+rs1knS1BmKS31MPvqXjnIqN0QzCjvV3BqnRFjkLa7QUVPTCT6xr/HO6cd7veBSOtM11UKbXkj/yCMhVChNrHcWWVB8qB8k9lPWMcp3UXEEyTBDjw0LZia9XMwAjv8rK+ujxaj0buSf5hbwuy2/DCkSBxv3UGfh+91ozkM="
  - secure: "bsgFcel/jDa/FOjST43Nv02LHWF1XwXi7pYLVxA7do5cmRSB5UbqUdLmQPEP2nF4jSYBY2ZUtZDe/wVy7prd1D1r7RnZXUyWdwpKRIxFluZWe4K9I4BYiDT3Owb+U8Mc/CdGlpP5C2iEDJPURCkGj7cEJXq+qT2S1pm8J8OA5ko="

before_install: _scripts/before_install.sh
script: _scripts/script.sh

after_success:
- echo "Host deploy_server" >> ~/.ssh/config
- echo "    Hostname ${SSH_HOST}" >> ~/.ssh/config
- echo "    User ${SSH_USER}" >> ~/.ssh/config
- echo "    Port ${SSH_PORT}" >> ~/.ssh/config
- echo "    StrictHostKeyChecking no" >> ~/.ssh/config
- echo "    CheckHostIP no" >> ~/.ssh/config
- echo "    UserKnownHostsFile=/dev/null" >> ~/.ssh/config

- echo -n "$id_rsa_{1..5}" >> ~/.ssh/id_rsa
- chmod 0700 ~/.ssh/id_rsa
- yes '
' | rsync -avz ./_site/* deploy_server:~/mysite/
