language: ruby
rvm:
- 1.9.3
env:
  global:
  - secure: RNCjMCt/irszSXGjZd/iagndvxgRSrSYuwhtJhBUc/mLnexH6iKOw6DYpNQN5i2uk6kP2xIVWx4OeyioqfO9Iz1cbGTgIv7GBbzaDLgH+QvmZwh1Gf6v5DCVI/G1OnyeCAYIGGum8wh+/945lJn/2yUSk0QmgJyEJr4Gw4hZUe8=
  - secure: akTV2pJh75NhiyW/FIqHMy9JpYVUuUVKYcHTnKRHbyvru2I4IfhBly75+LvkEWELP7uxPt3P9AirYmwdWadeG08FoHPQszhYaZ5aydaoj2m+0b0tAWmtf0WjfNkpoSjAqkLZuetUMyGZsmC9lzfS56OzRo4q6DOv+Q5xvKv5idY=
  - secure: PQ/nRmHIkiIUWTRrSU4yhTcJKrljYJ/MydXPWQgef8pLOUBELVUgeSg3j9I495b6UVmiwNF3QMzlvBRiBXTYAKscEMYz9fS0Y4TsrqQJEJb1s0mNjaqfKMqkWE63I3Boc+F6vCR4wAI1cNEMkDX/M8zFaXsRBQwf077nQn+apDY=
  - secure: bZq6eMXlr4Zq8bZSNCBAup0y2b/nw7Qd3AJ1qw3Un2nthtFhThZxCnhtf6M/ayLMjN6TyYbq0J+qaxb9akZ0XnkRCWrmwtLjC2zHqfOzUDB8x/n9uxiJ1UAhuvPnN00CdkFga/3ezpgU71FQ6YBZ4zZS1O2mGBPdM9LPjD5sd1M=
  - secure: RD/eyHDwJKGuEW+p5JsiRoJsEz1EDhaRlwiT6GJnAFfdi/ZAcyJaNNO1iulJwkd2M8lM9NcP1Q+urHc85wq7neUtNkSIMcIShgtnbhYdApZMyicRSOSeUS+rDQgbaP9p/IQ1EjqIJsPHmA139Fw/xKOGznzNM2a0UQlBjwBxBtw=
  - secure: RA7jV6DFIvsC25ly+jm7dfJzY3MY68f26jHHMLxYM+pUKK4gQ8UXZgYnJt1vsrvdFjmfJ52+qVQvPjeCG7B2a9glIcBtfKGzatUlKYQHZlmYP9mBe78J1ZgapuyqkOtZRas8XPdDwyhCiHxiQWX5budYin+AmDRnCMkSq2JJdVI=

before_install:
  - git submodule update --init --recursive

script:
  - jekyll build
  - mv ./_binaries/* ./_site
  - ls -aR ./_site/*

after_success:
  - echo "Host deploy_server" >> ~/.ssh/config
  - echo "Hostname ${SSH_HOST}" >> ~/.ssh/config
  - echo "User ${SSH_USER}" > ~/.ssh/config
  - echo "Port ${SSH_PORT}" > ~/.ssh/config
  - echo "StrictHostKeyChecking no" >> ~/.ssh/config
  - echo "CheckHostIP no" >> ~/.ssh/config
  - echo "UserKnownHostsFile=/dev/null" >> ~/.ssh/config
  
  - echo -n $id_rsa_{1..5} >> ~/.ssh/id_rsa
  - rsync -raz ./_site/* deploy_server:~/mysite/
