language: ruby
rvm:
- 1.9.3
env:
  global:
  - secure: giJwAh19ffZZ+Dv68BIsZ+1Mf9D4M06xOeJkOGkbh8cPMCEL1aJ140e0wK7a/g+Om3eEt4rhm0hmI53z8H35m75cgYbhrhwIiyyY+uD/TfLkDqwssdNNyWVN/cMAWpVuSmTS4GR6p0PTUDcL7gRadb0qtRp033bvAjxFkcJXc/k=
  - secure: IDJyV6F2YipKHXHLxW4IUGqO5kFPPMHLSjsmE1+QwZ4UeObZLLWQcIYSmifn+ySgnFoBDHD1aPw+h/ljbrM7L5om9ENxb457Nm5e3QMUVF5z7egy3C23EoHdijEmf3l0by1O72lpw3zJgOaAgDNZDLWhwC/lB/OAW6urCoE2s/c=
  - secure: eGJkeG11ZxVE67IKf7oARtvMGVDfowz5P8+X8tyKM5MhJ5ILFwEsjhHgW/hi3STTFbV26dqETXiMISWaiZdL1igMUbvpxwfcRw0RYYBmq4gKdCL4TZz2mLjixdnTDqzyvN4lJt8T2uF7mLSI9YsT1xyGT/snG+qzsPbrTQlS85A=
  - secure: OzA0aAiIYNI05Nmkm0JhbU2sdzNjmNhar2mo3e7W1Kv0CIae0LA1UujWIG1zNeiXBU9QTY/bh9AROeo81QSLhaeO+SwGlz2t43FmhDAR2K8/KySIsxPF79SlRAA9jrBVJ6QGeL2+IRT1QxD/BHjiKukIIJw1iGOf8J/ge7a2YnQ=
  - secure: FLgteTCbuOIPjciAbMWG59z0daozkZJvaI+TiqayEmHhdtnhO6nWaIqTIS3ytS7TC9IVC64hnoWgqgu8cAVviBOFMi/p88gVBuBeGYAHl6YWmUYHAJ/oAcJFZ5OuzSzZZ0FeqOzZMMjC08hN3MDAEqug/3ps36Kn5MebvPDbfTM=

  - secure: "BJNqCYEwZW+GKu8i5rfjd4wC6Scf5+KLTDkmuamYvY40CaYNSINFbNYOg8nrpwUkzcCcCgH7dtE5Ir5LiEqoYCYxLZoOKrNLIAg3/snNflP+qd4yY5lh9iWyGQcCw9Vg3Kq6ubVFkuO9nKfZv8pRoQZ/Tj73BtsEBL+OeDz51no="
  - secure: "CAQaP+rs1knS1BmKS31MPvqXjnIqN0QzCjvV3BqnRFjkLa7QUVPTCT6xr/HO6cd7veBSOtM11UKbXkj/yCMhVChNrHcWWVB8qB8k9lPWMcp3UXEEyTBDjw0LZia9XMwAjv8rK+ujxaj0buSf5hbwuy2/DCkSBxv3UGfh+91ozkM="
  - secure: "bsgFcel/jDa/FOjST43Nv02LHWF1XwXi7pYLVxA7do5cmRSB5UbqUdLmQPEP2nF4jSYBY2ZUtZDe/wVy7prd1D1r7RnZXUyWdwpKRIxFluZWe4K9I4BYiDT3Owb+U8Mc/CdGlpP5C2iEDJPURCkGj7cEJXq+qT2S1pm8J8OA5ko="

before_install:
- git submodule update --init --recursive

script:
- jekyll build
- mv ./_binaries/* ./_site
- ls -aR ./_site/*

after_success:
- echo "Host deploy_server" >> ~/.ssh/config
- echo "    Hostname ${SSH_HOST}" >> ~/.ssh/config
- echo "    User ${SSH_USER}" >> ~/.ssh/config
- echo "    Port ${SSH_PORT}" >> ~/.ssh/config
- echo "    StrictHostKeyChecking no" >> ~/.ssh/config
- echo "    CheckHostIP no" >> ~/.ssh/config
- echo "    UserKnownHostsFile=/dev/null" >> ~/.ssh/config

- echo -n $id_rsa_{1..5} >> ~/.ssh/id_rsa
- chmod 0700 ~/.ssh/id_rsa
- rsync -avz ./_site/* deploy_server:~/mysite/
