# NixTuts Jekyll configuration
title: NixTuts
permalink: /:categories/:title.html
pygments: true

# Exclude files
# .files are ignored by default
exclude: ["README.md", "Gemfile"]

# Excerpts
excerpt_separator: "<!--more-->"
